language: scala
jdk:
    - oraclejdk8
scala:
    - 2.11.7
before_install:
    - sudo apt-get -qq update

script: 
    - cd ./scalajs-plugin/
    - chmod +x gradlew
    - ./gradlew install
    - cd ../scalajs-plugin-test/
    - chmod +x gradlew

    #Testing current development version
    - ./gradlew RunJS -Pclassname="main.scala.Test" -Pmethname="printSomething(\"blabla\")" -Psnapshot
    - ./gradlew RunJS -Pclassname="main.scala.ScalaTagTest" -Psnapshot
    - ./gradlew CleanAll -Psnapshot
    - ./gradlew RunJS -PtoExec="main.scala.Test().main()\nmain.scala.ScalaTagTest().main()" -PrunFull -Psnapshot
    - ./gradlew CleanAll -Psnapshot
    - ./gradlew RunJS -PtoExec="main.scala.Test().main()" -Pclassname="main.scala.ScalaTagTest" -PrunNoOpt -Psnapshot
    - ./gradlew CleanAll -Psnapshot

    #Testing current release version
    - ./gradlew RunJS -Pclassname="main.scala.Test" -Pmethname="printSomething(\"blabla\")"
    - ./gradlew CleanAll
    - ./gradlew RunJS -Pclassname="main.scala.ScalaTagTest" -PrunFull
    - ./gradlew CleanAll
    - ./gradlew RunJS -Pclassname="main.scala.ScalaTagTest" -PrunNoOpt
    - ./gradlew CleanAll
    - ./gradlew RunJS -Pclassname="main.scala.Test" -PrunFull -PrunNoOpt
    - ./gradlew CleanAll

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/