language: scala
jdk:
    - oraclejdk8
scala:
    - 2.11.7
before_install:
    - sudo apt-get -qq update

script: 
    - cd ./scalajs-test/
    - chmod +x ./gradlew
    - ./gradlew runJS -Pclassname=main.scalajs.ScalaTagTest --i
    - ./gradlew cleanAll --i

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/