language: scala
jdk:
    - oraclejdk8
scala:
    - 2.11.7
before_install:
    - sudo apt-get -qq update

script: 
    - cd ./scalajs-plugin/
    - chmod +x gradlew
    - ./gradlew install
    - cd ../scalajs-plugin-test/
    - chmod +x gradlew

    - ./gradlew RunJS -Pclassname="main.scala.Test" -Pmethname="printSomething(\"blabla\")"
    - ./gradlew RunJS -Pclassname="main.scala.ScalaTagTest"
    - ./gradlew CleanAll
    - ./gradlew RunJS -PtoExec="main.scala.ScalaTagTest().main()" -PrunFull
    - ./gradlew CleanAll
    - ./gradlew RunJS -PtoExec="main.scala.Test().main()" -Pclassname="main.scala.ScalaTagTest" -PrunNoOpt
    - ./gradlew CleanAll


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/