language: scala
jdk:
    - oraclejdk8
scala:
    - 2.11.8
before_install:
    - sudo apt-get -qq update

script: 
    - cd ./scalajs-plugin/
    - chmod +x gradlew
    - ./gradlew install
    - ./gradlew build
    - cd ../scalajs-plugin-test/
    - chmod +x gradlew

    - ./gradlew RunJS -Pclassname="main.scala.Test" -Pmethname="printSomething(\"blabla\")" -Prhino
    - ./gradlew RunJS -Pclassname="main.scala.ScalaTagTest" -Pphantom
    - ./gradlew CleanAll
    - ./gradlew RunJS -PtoExec="main.scala.ScalaTagTest().main()" -PrunFull -Prhino
    - ./gradlew CleanAll
    - ./gradlew RunJS -PtoExec="main.scala.Test().main()" -Pclassname="main.scala.ScalaTagTest" -PrunNoOpt
    - ./gradlew CleanAll
    - ./gradlew RunJS -PfileToExec="testjs/testRunWithFile.js" -PrunFull -Pphantom
    - ./gradlew RunJS -PfileToExec="testjs/testRunWithFile.js" -PrunNoOpt -Prhino
    - ./gradlew RunJS -PfileToExec="testjs/testRunWithFile.js"


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/