language: scala
jdk:
    - oraclejdk8
scala:
    - 2.11.7
before_install:
    - sudo apt-get -qq update

script: 
    - chmod +x ./scalajs-test/gradlew
    - ./scalajs-test/gradlew runJS -Pclassname=main.scalajs.ScalaTagTest --d
    - ./scalajs-test/gradlew cleanAll --d

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/