language: scala
jdk:
    - oraclejdk8
scala:
    - 2.11.7
before_install:
    - sudo apt-get -qq update

script: 
    - cd ./scalajs-plugin/
    - chmod +x ./gradlew
	- ./gradlew install
	- cd ../scalajs-plugin-test/
	- chmod +x ./gradlew
    - ./gradlew runJS -Pclassname=main.scalajs.ScalaTagTest
    - ./gradlew cleanAll

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/